callstack/react-native-visionos

README.md, packages/react-native/Libraries/Components/Pressable/Pressable.js, packages/react-native/Libraries/Components/Touchable/TouchableOpacity.d.ts, packages/react-native/Libraries/Components/View/ViewPropTypes.d.ts, packages/react-native/Libraries/Components/View/ViewPropTypes.js, packages/react-native/React/Views/RCTViewManager.h
This PR renames VisionOS to visionOS so it matches official OS name (https://developer.apple.com/documentation/visionos)
=> chore: change VisionOS to visionOS

packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm, packages/react-native/React/CoreModules/RCTDeviceInfo.mm, packages/react-native/React/CoreModules/RCTStatusBarManager.mm, packages/react-native/React/Views/RCTWrapperViewController.m, packages/react-native/React/Views/ScrollView/RCTScrollViewManager.h, packages/react-native/React/Views/ScrollView/RCTScrollViewManager.m, packages/rn-tester/RNTester/AppDelegate.mm
This PR reduces code diff between visionos and core. It also removes some not needed checks. 
[INTERNAL] [REMOVED] - Remove not needed TARGET_OS_VISION ifs 
Check if the app runs.
=> chore: remove not necessary ifs `TARGET_OS_VISION`, minimise code diff

packages/react-native/Libraries/Components/Keyboard/Keyboard.js, packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js, packages/react-native/React/CoreModules/RCTKeyboardObserver.mm
Fixes #6 
Mark `Keyboard.js` and `KeyboardAvoidingView.js` as unsupported and remove listeners in `RCTKeyboardObserver.mm`, because VisionOS displays the keyboard in a separate window, leaving the app window unaffected.
[VISIONOS] [ADDED] - warning about unavailable Keyboard
[VISIONOS] [ADDED] - warning about unavailable KeyboardAvoidingView
[VISIONOS] [CHANGED] - early return when adding and removing listeners in Keyboard
[VISIONOS] [CHANGED] - return passthrough View when rendering KeyboardAvoidingView on VisionOS
[VISIONOS] [CHANGED] - do nothing if TARGET_OS_VISION in `startObserving` and `stopObserving`
1. Open KeyboardAvoidingView in RNTester
2. Verify warn is displayed in the app and in the Metro logs
3. Verify examples should still load and function correctly
=> fix: remove keyboard listerners and mark as unsupported

packages/react-native/Libraries/Image/React-RCTImage.podspec, packages/react-native/Libraries/LinkingIOS/React-RCTLinking.podspec, packages/react-native/Libraries/NativeAnimation/React-RCTAnimation.podspec, packages/react-native/Libraries/PushNotificationIOS/React-RCTPushNotification.podspec, packages/react-native/ReactCommon/react/nativemodule/samples/ReactCommon-Samples.podspec, packages/react-native/ReactCommon/react/renderer/graphics/React-graphics.podspec, packages/rn-tester/NativeModuleExample/ScreenshotManager.podspec
This PR brings support for building visionOS with `use_frameworks! :linkage => dynamic`.
By default RN builds static libraries however, Xcode does not support building static libraries that include Swift code which is a major blocker for us (as we want to include Swift). 
[VISIONOS] [FIXED] - Support building the app with dynamic `use_frameworks`
Check if RNTester is building with `use_frameworks`
=> feat: support building visionOS with dynamic frameworks enabled

README.md, packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb, packages/react-native/sdks/hermes-engine/utils/build-hermes-xcode.sh, packages/react-native/sdks/hermes-engine/utils/create-dummy-hermes-xcframework.sh, packages/rn-tester/Podfile, packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
This PR is still WIP. I've managed to properly link hermes for `xros` (real device) but it's still failing to link it for simulator. 
**Note: You will need to install CMake from source to be able to build hermes**
```sh
brew install cmake --head
```
This PR is also based on my hermes fork but I will contribute changes from the fork when I got it working
=> feat: make hermes build for visionOS

.circleci/configurations/test_workflows/testAndroid.yml, .circleci/configurations/test_workflows/testE2E.yml, .circleci/configurations/test_workflows/testIOS.yml, .circleci/configurations/test_workflows/testJS.yml, .circleci/configurations/workflows.yml, .github/workflows/ios-tests.yml, packages/react-native/Libraries/Components/Keyboard/Keyboard.js, packages/react-native/Libraries/Components/Pressable/__tests__/__snapshots__/Pressable-test.js.snap, packages/react-native/Libraries/Components/Touchable/__tests__/__snapshots__/TouchableOpacity-test.js.snap, packages/react-native/Libraries/Components/__tests__/__snapshots__/Button-test.js.snap, packages/react-native/Libraries/Utilities/Platform.android.js, packages/react-native/Libraries/Utilities/Platform.flow.js, scripts/circleci/pipeline_selection.js
Due to high usage of CircleCI limits we are disabling some of not needed CircleCI pipelines
=> chore: disable some of upstream pipelines

README.md
This PR adds platform guidelines to the README
=> Add platform guidelines to README

packages/react-native/Libraries/Components/StatusBar/StatusBar.js, packages/react-native/React/CoreModules/RCTStatusBarManager.mm
[Issue](https://github.com/callstack/react-native-visionos/issues/9)
Mark StatusBar as unsupported given VisionOS doesn't have a concept of StatusBar.
[VISIONOS] [ADDED] - warning about unavailable StatusBar
[VISIONOS] [CHANGED] - do nothing if TARGET_OS_VISION in stopObserving
1. Open StatusBar in RNTester
2. Verify warn is displayed in the app and in the Metro logs
=> task(StatusBar component): show warn when using StatusBar

packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTFabricModalHostViewController.mm, packages/react-native/React/UIUtils/RCTUIUtils.m, packages/react-native/React/Views/RCTModalHostView.m
Goal of this PR is to align compiler conditionals `TARGET_OS_VISION` in our fork. There were places were those conditionals are not needed due to upstream contributions.
[INTERNAL] [FIXED] - Align `TARGET_OS_VISION` conditionals
CI Green
=> feat: align unnecessary compiler conditionals

packages/out-of-tree-platforms/package.json, packages/out-of-tree-platforms/src/getPlatformResolver.js, packages/out-of-tree-platforms/src/index.js, packages/rn-tester/package.json
This PR should fix issues with running local RNTester app while packages are not built. For some reason RN core is not running a `postinstall` script that builds the packages so `@callstack/out-of-tree-platforms` wasn't built after cloning the repo. 
[INTERNAL] [FIXED] - fix: local build of RNTester with `@callstack/out-of-tree-platforms`
CI Green
=> fix(#48) local build of `@callstack/out-of-tree-platforms`

packages/react-native/sdks/hermes-engine/utils/build-hermesc-xcode.sh
This PR adds error to Hermes build phase that we need at least CMake 3.28.0 to build visionOS.
[VISIONOS] [ADDED] - Error out on CMake 3.28.0 being required
Build Hermes with unsupported version of CMake
=> feat: add error about CMake 3.28.0 being required

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
This PR removes `GlassViewController` which is no longer needed, minimizing fork surface. Looks like in the latest Beta Glass appearance is set by default.
[VISIONOS] [REMOVED] - `GlassViewController`
Check if the app has glass appearance
=> remove: GlassViewController is no longer needed

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Views/RCTView.m
This PR is an experimental fix for #12 . In this PR I have added method to apply the borderRadius style which is applied to View to hoverStyle. Currently I have added support for borderRadius style. But for other cases like borderTopEndRadius, borderTopStartRadius will not work.
[VISIONOS] - added method to apply borderRadius to hoverStyle
=> added cornerRadius for hover style

packages/community-cli-plugin/package.json, packages/react-native/local-cli/localCommands.js, packages/react-native/package.json, packages/react-native/react-native.config.js, packages/react-native/template/package.json, yarn.lock
This PR implements: `run-visionos`, `build-visionos` and `log-visionos` CLI commands.
This PR needs `cli-platform-apple` to be released
[VISIONOS] [ADDED] - visionOS CLI commands
Test new CLI commands in initialized project
=> feat: implement visionos cli commands

packages/react-native/Libraries/Components/Keyboard/Keyboard.js, packages/react-native/Libraries/Components/ScrollView/ScrollView.js
This PR moves the warnOnce to the addEventListener() method of KeyboardAPI. This avoids informing users multiple times about the keyboard API being unavailable. Also, I removed the usage of Keyboard API from ScrollView.js to avoid emitting this warning from our code. 
[VISIONOS] [FIXED] - Don't warn users about the Keyboard API all the time
CI Green
=> fix: don't warn users about the Keyboard API all the time

packages/react-native/Libraries/Components/Keyboard/Keyboard.js, packages/react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js, packages/react-native/Libraries/Components/ScrollView/ScrollView.js, packages/react-native/Libraries/Components/StatusBar/StatusBar.js, packages/react-native/Libraries/Components/TextInput/InputAccessoryView.js, packages/react-native/Libraries/Utilities/Platform.android.js, packages/react-native/Libraries/Utilities/Platform.flow.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap, packages/rn-tester/Podfile.lock
This PR renames from `isVisionOS` to recently upstreamed `isVision`.
[VISIONOS] [CHANGED] - Use `isVision` instead of `isVisionOS`
CI Green
=> fix: use isVision instead of isVisionOS

packages/react-native/scripts/react-native-xcode.sh, packages/react-native/template/visionos/HelloWorld.xcodeproj/project.pbxproj
This PR fixes the release bundle that wasn't using the react-native-visionos JS source code + we didn't pass the custom resolver option. 
Closes: #73 
[VISIONOS] [FIXED] - release bundle build 
CI Green, release bundle has hover effects
=> fix: release build bundle

packages/react-native/Libraries/Utilities/Platform.android.js
This PR removes duplicated `isVision` key in Platform.android.js
=> fix: remove duplicated isVision key

scripts/new-github-release-url.js, scripts/oot-release.js
This PR adds release scripts to automate the release of `react-native-visonos` and publish changelog on GitHub releases. I've tried with a pre-made package called release-it but it had a conflicting dependency that made some tests fail.
=> feat: add release scripts for GitHub releases

README.md
This PR corrects capitalization issues in README
=> fix: update README.md with corrected capitalization

scripts/oot-release.js
This PR adjusts oot-release script for stable releases, it's mostly cherry-picks from `0.73-stable`
=> fix: adjust oot-release script for stable releases

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Views/RCTView.m
This PR fixes an issue where providing an unsupported value like `visionos_hoverEffect="test"` crashed the app.
[VISIONOS] [FIXED] - Prevent app crash with unsupported values for hoverEffect
=> fix: providing unsupported value to hoverStyle crashed the app

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
This PR fixes running (visionOS) RNTester in bridgeless mode
=> fix: running RNTester in bridgeless mode on visionOS

packages/react-native/React/Base/RCTUtils.h, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/UIUtils/RCTUIUtils.m
This PR removes unused `RCTForegroundWindow`, this became obsolete after introducing SwiftUI as the root #77
=> refactor: remove unused RCTForegroundWindow

packages/react-native/React/CoreModules/RCTDevMenu.mm
This PR fixes the retrieval of RCTKeyWindow when clicking either "Show Perf Monitor" or "Configure bundler". For some reason, the window was nil when we were calling this method in between closing the Dev Menu. Adding 0ms timer executes this code later (next loop) and thanks to this the window is properly retrieved.
=> fix: properly retrieve window when clicking DevMenu action

packages/react-native/React/Fabric/RCTSurfacePointerHandler.mm, packages/react-native/React/Fabric/RCTSurfaceTouchHandler.mm
This PR fixes pointer events for visionOS (#21)
=> fix: pointer events

README.md
This PR removes most of the documentation from README in order to switch to the documentation page: https://callstack.github.io/react-native-visionos-docs/
=> docs: move to documentation website

README.md
The getting started link in the readme led to a 404.
[GENERAL] [FIXED] - Updated getting started link in readme.
I followed the new link and it works now!
=> chore: update getting started link in Readme.

packages/react-native/Libraries/Components/Pressable/Pressable.js, packages/react-native/Libraries/Components/Pressable/__tests__/__snapshots__/Pressable-test.js.snap, packages/react-native/Libraries/Components/Touchable/TouchableHighlight.js, packages/react-native/Libraries/Components/Touchable/TouchableOpacity.d.ts, packages/react-native/Libraries/Components/Touchable/TouchableOpacity.js, packages/react-native/Libraries/Components/Touchable/__tests__/__snapshots__/TouchableHighlight-test.js.snap, packages/react-native/Libraries/Components/Touchable/__tests__/__snapshots__/TouchableOpacity-test.js.snap, packages/react-native/Libraries/Components/View/ReactNativeStyleAttributes.js, packages/react-native/Libraries/Components/View/ViewNativeComponent.js, packages/react-native/Libraries/Components/View/ViewPropTypes.d.ts, packages/react-native/Libraries/Components/View/ViewPropTypes.js, packages/react-native/Libraries/Components/__tests__/__snapshots__/Button-test.js.snap, packages/react-native/Libraries/StyleSheet/StyleSheetTypes.d.ts, packages/react-native/Libraries/StyleSheet/StyleSheetTypes.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap, packages/react-native/React/Base/RCTConvert.h, packages/react-native/React/Base/RCTConvert.m, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Views/RCTCursor.h, packages/react-native/React/Views/RCTView.h, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/RCTViewManager.m, packages/react-native/ReactCommon/react/renderer/components/view/BaseViewProps.cpp, packages/react-native/ReactCommon/react/renderer/components/view/BaseViewProps.h, packages/react-native/ReactCommon/react/renderer/components/view/conversions.h, packages/react-native/ReactCommon/react/renderer/components/view/primitives.h, packages/rn-tester/js/examples/Cursor/CursorExample.js, packages/rn-tester/js/utils/RNTesterList.ios.js
This PR removes `visionos_hoverEffect` prop which is about to be replaced with `cursor: pointer` style.
Next steps involve cherry picking https://github.com/facebook/react-native/pull/43078
=> chore: remove hover effect & add cursor: pointer

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
This PR changes the background color to clearColor for visionOS. This makes app background a little lighter: 
[VISIONOS] [CHANGED] - use clearColor instead of systemBackgroundColor for visionOS
Check if app background is now lighter
=> fix: use clearColor instead of systemBackgroundColor for visionOS

packages/react-native/sdks/hermes-engine/utils/build-hermes-xcode.sh, packages/react-native/template/visionos/HelloWorld/AppDelegate.swift
This PR fixes Hermes build scripts + unnecessary optional check `?` form AppDelegate. (Mostly picks from 0.74.0-rc.0)
CI Green
=> fix: hermes xcode build scripts

packages/react-native/local-cli/localCommands.js
This PR fixes local commands parameters and allows to pass the same parameters that `run-ios` accepts.
=> fix: local commands parameters

packages/react-native/Libraries/SwiftExtensions/RCTMainWindow.swift
This PR exposes `WindowHandlingModifier` in order to allow users to ditch `RCTMainWindow` and use custom setup (for example when they want to add ornaments on main window).
```swift
@main
struct RC07401VISIONOSApp: App {
@UIApplicationDelegateAdaptor var delegate: AppDelegate
var body: some Scene {
WindowGroup {
RCTRootViewRepresentable(moduleName: "RC07401VISIONOS", initialProps: nil)
.modifier(WindowHandlingModifier())
// Add ornaments 
}
}
}
```
Resolves #136 
[VISIONOS] [ADDED] - Expose WindowHandlingModifier
CI Green
=> feat: allow to use WindowHandlingModifier outside of RCTMainWindow

packages/react-native/Libraries/LinkingIOS/RCTLinkingManager.h, packages/react-native/Libraries/LinkingIOS/RCTLinkingManager.mm, packages/react-native/Libraries/SwiftExtensions/RCTMainWindow.swift, packages/rn-tester/RNTester-visionOS/App.swift, packages/rn-tester/RNTester-visionOS/Info.plist
This PR allows to use deeplinks/universal links in React Native visionOS apps. 
In order to use this feature, users need to add this modifier to their App.swift file: 
```swift
@main
struct RNTesterApp: App {
@UIApplicationDelegateAdaptor var delegate: AppDelegate
var body: some Scene {
RCTMainWindow(moduleName: "RNTesterApp")
.onOpenURL(perform: { url in
RCTLinkingManager.onOpenURL(url: url)
})
}
}
```
A more in-depth documentation page will be created.
Thanks to @thiagobrez for investigating this one and helping me with the implementation and testing 🙏
[VISIONOS] [ADDED] - Support for deep links / universal links
Check if deeplink is opening the app
=> fix: deep and universal links 

packages/react-native/Libraries/SwiftExtensions/RCTMainWindow.swift, packages/react-native/Libraries/SwiftExtensions/RCTWindow.swift, packages/react-native/Libraries/WindowManager/RCTWindowManager.h, packages/react-native/Libraries/WindowManager/RCTWindowManager.mm, packages/react-native/Libraries/WindowManager/WindowManager.d.ts, packages/react-native/Libraries/WindowManager/WindowManager.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap, packages/react-native/src/private/specs/visionos_modules/NativeWindowManager.js, packages/rn-tester/js/examples/XR/XRExample.js
This PR implements window manager events, which solves #135. 
Users will be able to listen to window state changes: 
```tsx
React.useEffect(() => { 
const listener = WindowManager.addEventListener('windowStateDidChange', (data) => {
console.log('Window state changed to:', data);
});
return () => {
listener.remove();
};
}, []);
```
The main window always has the id: `0`
[VISIONOS] [ADDED] - Implement window manager events
CI Green
=> feat: implement window manager events

packages/react-native/Libraries/Components/ScrollView/ScrollView.js
Hi! I am hitting an issue where the keyboard warning keeps popping up no matter what I do and I tracked it down to ScrollView.js.
In https://github.com/callstack/react-native-visionos/pull/71/ it was mentioned that the keyboard api was to be avoided if in visionOS but I think it currently is doing the opposite. I've tested this proposed change in simulator/device and it seems to be good, but maybe I'm understanding this wrong so feel free to close this PR if not! Thanks!
Before:
After:
To test, add a ScrollView in any app and see that the api error happens. You'll need to make sure metro refreshes the app to see the error since the warn once is currently working as intended.
=> Prevent Keyboard API in ScrollView

packages/react-native/template/visionos/HelloWorld.xcodeproj/project.pbxproj, packages/react-native/template/visionos/HelloWorld/PrivacyInfo.xcprivacy
This commit includes privacy info manifest for visionOS apps. 
Based on this upstream commit: 
https://github.com/facebook/react-native/commit/520d120375c6b24bc161adea4f48d76537a34abc
[VISIONOS] [ADDED] - Privacy Info manifest
Create new project and check if privacy info is properly added
=> feat: include privacy info manifest

packages/react-native/Libraries/SwiftExtensions/RCTMainWindow.swift, packages/react-native/Libraries/SwiftExtensions/RCTWindow.swift, packages/react-native/Libraries/WindowManager/RCTWindowManager.h, packages/react-native/Libraries/WindowManager/RCTWindowManager.mm, packages/react-native/Libraries/WindowManager/WindowManager.d.ts, packages/react-native/Libraries/WindowManager/WindowManager.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap, packages/react-native/src/private/specs/visionos_modules/NativeWindowManager.js, packages/rn-tester/js/examples/XR/XRExample.js
This API was not useful because you can achieve the same thing with AppState (visionOS doesn't differentiate between focused windows as I thought it does). 
It never got released so I'm reverting the implementation.
=> Revert "feat: implement window manager events (#142)"

packages/react-native/Libraries/SwiftExtensions/RCTMainWindow.swift, packages/react-native/Libraries/SwiftExtensions/RCTRootViewRepresentable.swift, packages/react-native/Libraries/SwiftExtensions/RCTWindow.swift
This PR allows users to move dev menu to avoid conflicts with their custom ornaments.
[VISIONOS] [ADDED] - allow to manually move dev menu to avoid conflicts
Test if dev menu ornament can be moved
=> fix: allow to manually move dev menu to avoid conflicts

packages/react-native/Libraries/LinkingIOS/React-RCTLinking.podspec, packages/react-native/Libraries/NativeAnimation/React-RCTAnimation.podspec, packages/react-native/ReactCommon/react/renderer/graphics/React-graphics.podspec, packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/utils/build-hermes-xcode.sh
This PR removes some unnecessary diffs from our fork, that we can remove thanks to upstreaming.
CI Green
=> fix: remove unnecessary diff after upstreaming changes

packages/react-native/Libraries/Components/Pressable/Pressable.js, packages/react-native/Libraries/Components/Pressable/__tests__/__snapshots__/Pressable-test.js.snap, packages/react-native/Libraries/Components/Touchable/TouchableHighlight.js, packages/react-native/Libraries/Components/Touchable/TouchableOpacity.js, packages/react-native/Libraries/Components/Touchable/__tests__/__snapshots__/TouchableHighlight-test.js.snap, packages/react-native/Libraries/Components/Touchable/__tests__/__snapshots__/TouchableOpacity-test.js.snap, packages/react-native/Libraries/Components/__tests__/__snapshots__/Button-test.js.snap
This PR removes the automatic cursor pointer.
Cursor pointer should now be applied by users in Stylesheet.
This feature has been upstreamed to React Native Core, originating from this repository. Current behavior of this prop upstream is **opt-in** not opt-out as visionOS was doing. 
If at some point in the future, we get closer to merging visionOS support inside of React Native core this feature is going to be dropped anyways.
[IOS] [DEPRECATED] - Don't apply the cursor pointer automatically
CI Green
=> chore: remove automatic cursor pointer

.github/actions/test-visionos-rntester/action.yml
MacOS-14 runners no longer have the VisionOS SDK pre-installed, so we must download it prior to building for VisionOS: https://github.com/actions/runner-images/issues/10559. We can use the same solution as React Native Test App: https://github.com/microsoft/react-native-test-app/pull/2258/files
- Adds a step to the VisionOS test runner to download the VisionOS SDK before attempting to build with XCode 
Pick one each for the category and type tags:
[VISIONOS] [FIXED] 
- CI should pass after this change
=> fix: Manually download VisionOS SDK in CI
